Unify docker-build-image and docker-manifest in single workflow (#16)
* adding fixes

* Add build-docker unified

* some minor changes

* Improve resiliance

* Tunning the workflow

* fix smoke tests

* Update names

* fix: Group concurrency

* minor change

* Start debugging package.json

* Fixing package.json

* add more dependencies

* fix: Matrix job outputs will only retain the value from the last leg to complete

* fixing code rabbit suggestions

* Improve docs

* use tag again

* Use cosign installer action

* Fix trivy scan

* Fix checkout

* Setup git credentials for private repositories

* remove extra new lines

* Remove debugging

* Add nix to the release-action

* fix docs

* Change scan Trivy model

* Add permission

* Exclude 0 vulnerabilities

* add docs

* Using sed

* remove permissions

* use json format

* add id-token

* Add workload identity configuration to setupGCP

* add latest changes

* Use skopeo instead of docker

* refactoring

* Fixing policy

* Improve Trivy scan parsing

* Fix concurrency

* Add docker_format_type

* Fix function

* fix string comparision

* Fix rate limiting on Trivy

* Use nixed version

* using nix

* Fix bumping cargo lock file

* fix double nix command

* Not print empty trivy reports

* Add build-library

* remove version_type

* Add support for `latest-release`

* rename workflow

* rename workflow's job

* remove debugging

* fix: GCP Identity provider

* Add token_format

* Add the new logic for lts

* fix: Fix building debug

* fix: commit hash

* fix: commit sha debug

* reorder tasks

* fix permissions

* build specific binaries

diff --git a/actions/set-build-version/action.yaml b/actions/set-build-version/action.yaml
--- a/actions/set-build-version/action.yaml
+++ b/actions/set-build-version/action.yaml
@@ -10,7 +10,7 @@ inputs:
         required: true
     architecture:
         description: 'Target architecture for the docker image'
-        required: true
+        required: false
         default: x86_64-linux
 outputs:
     current_version:
@@ -28,6 +28,9 @@ outputs:
     release_version:
         description: 'Release version'
         value: ${{ steps.versions.outputs.release_version }}
+    prerelease:
+        description: 'Whether the version is a prerelease'
+        value: ${{ steps.versions.outputs.prerelease }}
     build_version:
         description: 'Build version based on version type'
         value: ${{ steps.versions.outputs.build_version }}
@@ -65,13 +68,30 @@ runs:
         id: versions
         run: |
           echo "Gathering version from ${{ inputs.file }} and setting build version type to '${{ inputs.version_type }}'"
-          current_version=$(grep -E '^version\s*=' ${{ inputs.file }} | awk -F\" '{print $2}')
-          commit_version="$current_version+commit.$(git rev-parse --short HEAD)"
-          pr_version="$current_version+pr.${{ github.event.pull_request.number }}"
-          release_version="$current_version"
+          if [[ "${{ inputs.file }}" =~ ^.*\.toml$ ]]; then
+            current_version=$(grep -E '^version\s*=' ${{ inputs.file }} | awk -F\" '{print $2}')
+          elif [[ "${{ inputs.file }}" =~ ^.*\.json$ ]]; then
+            current_version=$(jq -r '.version' ${{ inputs.file }})
+          else
+            echo "Unsupported file type: ${{ inputs.file }}"
+            exit 1
+          fi
+          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
+            sha="${{ github.event.pull_request.merge_commit_sha }}"
+            commit_sha="${sha:0:7}"
+          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            sha="${{ github.event.pull_request.head.sha }}"
+            commit_sha="${sha:0:7}"
+          else
+            commit_sha=$(git rev-parse --short HEAD)
+          fi
+          commit_version="${current_version}+commit.${commit_sha}"
+          pr_version="${current_version}+pr.${{ github.event.pull_request.number }}"
+          release_version="${current_version}"
           publish_artifact_registry=false
           publish_github_release=false
           deploy_staging=false
+          prerelease=false
           if [[ "${{ inputs.version_type }}" == "commit" ]]; then
             build_version=${commit_version}
             if [ "${GITHUB_PR_LABEL_PUBLISH_BINARIES:-0}" == '1' ]; then
@@ -88,6 +108,9 @@ runs:
             build_version=${release_version}
             publish_github_release=true
             publish_artifact_registry=true
+            if [[ $current_version == *"-rc."* ]]; then
+              prerelease=true
+            fi
           else
             echo "Invalid version type"
             echo "Parameter version_type must be one of the following:"
@@ -99,7 +122,7 @@ runs:
 
           ## Debug build flavor
           if [[ "${{ inputs.version_type }}" == "commit" ]] && [[ "${GITHUB_PR_LABEL_BUILD_FLAVOR_DEBUG:-0}" == '1' ]]; then
-              debug_version="$current_version+debug.$(git rev-parse --short HEAD)"
+              debug_version="${current_version}+debug.${commit_sha}"
               docker_debug_version=${debug_version/+/-}
               if [[ "${{ inputs.architecture }}" == "aarch64-linux" ]]; then
                 docker_debug_version_platform="${docker_debug_version}-linux-arm64"
@@ -114,19 +137,22 @@ runs:
           # Generate Docker compatible version
           docker_build_version=${build_version/+/-}
           if [[ "${{ inputs.architecture }}" == "aarch64-linux" ]]; then
-            docker_build_version_platform="${docker_build_version}-linux-arm64"
             docker_platform="linux-arm64"
           elif [[ "${{ inputs.architecture }}" == "x86_64-linux" ]]; then
-            docker_build_version_platform="${docker_build_version}-linux-amd64"
             docker_platform="linux-amd64"
           else
+            # We are not supporting other architectures for docker images at the moment
+            # But we want to allow the action to be used for other architectures for non-docker builds, so we won't fail the action here. 
+            # Instead, we'll set the docker_platform to the input architecture and let the docker build step fail if it's not supported.
+            docker_platform="${{ inputs.architecture }}"            
             echo "Unsupported architecture: ${{ inputs.architecture }}"
-            exit 1
           fi
+          docker_build_version_platform="${docker_build_version}-${docker_platform}"
           echo "current_version=${current_version}" | tee -a "$GITHUB_OUTPUT"
           echo "commit_version=${commit_version}" | tee -a "$GITHUB_OUTPUT"
           echo "pr_version=${pr_version}" | tee -a "$GITHUB_OUTPUT"
           echo "release_version=${release_version}" | tee -a "$GITHUB_OUTPUT"
+          echo "prerelease=${prerelease}" | tee -a "$GITHUB_OUTPUT"
           echo "build_version=${build_version}" | tee -a "$GITHUB_OUTPUT"
           echo "docker_build_version=${docker_build_version}" | tee -a "$GITHUB_OUTPUT"
           echo "docker_build_version_platform=${docker_build_version_platform}" | tee -a "$GITHUB_OUTPUT"
@@ -135,11 +161,20 @@ runs:
           echo "publish_github_release=${publish_github_release}" | tee -a "$GITHUB_OUTPUT"
           echo "deploy_staging=${deploy_staging}" | tee -a "$GITHUB_OUTPUT"
       - name: Update build version
+        # Equivalent to:  inputs.version_type != 'release'
+        if: steps.versions.outputs.current_version != steps.versions.outputs.build_version
         shell: bash
         run: |
-          sed -i.bak -E "s/(^version = \")([0-9]+\.[0-9]+\.[0-9]+)(-rc\.[0-9]+)?(\+.*)?(\")/\1${{ steps.versions.outputs.build_version}}\5/" ${{ inputs.file }}
-          if [[ "${{ inputs.file }}" =~ .*Cargo\.toml$ ]]; then
-            echo "Regenerating Cargo.lock file"
-            nix develop --command cargo generate-lockfile
+          if [[ "${{ inputs.file }}" =~ .*\.toml$ ]]; then
+            sed -i.bak -E "s/(^version = \")([0-9]+\.[0-9]+\.[0-9]+)(-rc\.[0-9]+)?(\+.*)?(\")/\1${{ steps.versions.outputs.build_version}}\5/" ${{ inputs.file }}
+            rm "${{ inputs.file }}.bak"
+            if [[ "${{ inputs.file }}" =~ .*Cargo\.toml$ ]]; then
+              echo "Regenerating Cargo.lock file"
+              nix develop --command bash -c "cargo metadata --no-deps --format-version 1 --manifest-path ${{ inputs.file }} \
+                | jq -r '.packages[] | select(.source == null) | .name' \
+                | xargs -I{} cargo update -p {}"
+            fi
+          elif [[ "${{ inputs.file }}" =~ ^.*\.json$ ]]; then
+            jq --arg build_version "${{ steps.versions.outputs.build_version }}" '.version = $build_version' ${{ inputs.file }} > "${{ inputs.file }}.tmp"
+            mv "${{ inputs.file }}.tmp" ${{ inputs.file }}
           fi
-          rm "${{ inputs.file }}.bak"
